# Generated by Django 3.1 on 2020-11-21 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isNotice', models.BooleanField(default=True)),
                ('postUpdateDate', models.DateTimeField(auto_now_add=True)),
                ('postDetail', models.TextField()),
                ('postName', models.CharField(max_length=255)),
                ('postSubjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
                ('postUserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Post',
            },
        ),
    ]
