# Generated by Django 3.1 on 2020-11-21 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=255)),
                ('subjectTimeList', models.TextField()),
                ('invitationCode', models.CharField(max_length=64)),
                ('subjectInstructorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uid_for_instructor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Subject',
            },
        ),
    ]
