# Generated by Django 3.1 on 2020-11-25 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subject', '0005_auto_20201125_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='waitingList',
        ),
        migrations.AddField(
            model_name='subject',
            name='waitingUserId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='WaitingList',
        ),
    ]
