# Generated by Django 3.1 on 2020-11-26 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0007_auto_20201126_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='waitingUserId',
        ),
    ]
