# Generated by Django 3.1 on 2020-11-27 16:58

import assignment.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0008_remove_subject_waitinguserid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignmentName', models.CharField(max_length=255)),
                ('assignmentDetail', models.TextField(null=True)),
                ('assignmentFile', models.FileField(blank=True, null=True, upload_to=assignment.models.get_file_path, verbose_name='파일')),
                ('assignmentFileName', models.CharField(max_length=64, null=True, verbose_name='첨부파일명')),
                ('assignmentUpdateDate', models.DateTimeField(auto_now_add=True)),
                ('assignmentDueDate', models.DateTimeField()),
                ('subjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
            ],
            options={
                'db_table': 'Assignment',
            },
        ),
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitUpdateDate', models.DateTimeField(auto_now_add=True)),
                ('submitDetail', models.TextField(null=True)),
                ('submitFile', models.FileField(blank=True, null=True, upload_to=assignment.models.get_file_path, verbose_name='파일')),
                ('submitFileName', models.CharField(max_length=64, null=True, verbose_name='첨부파일명')),
                ('assignmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.assignment')),
                ('submitUserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Submit',
            },
        ),
    ]
