# Generated by Django 3.1 on 2020-11-28 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignmentFileName',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='첨부파일명'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='submitFileName',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='첨부파일명'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='submitUserId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
